set(_CATKIN_CURRENT_PACKAGE "offloadable_face_recognition")
set(offloadable_face_recognition_MAINTAINER "Justin McManus <jmcmanus1992@gmail.com>")
set(offloadable_face_recognition_DEPRECATED "")
set(offloadable_face_recognition_VERSION "0.0.0")
set(offloadable_face_recognition_BUILD_DEPENDS "message_generation" "rospy" "roscpp" "std_msgs" "sensor_msgs" "cv_bridge" "image_transport")
set(offloadable_face_recognition_RUN_DEPENDS "rospy" "roscpp" "message_runtime" "std_msgs" "sensor_msgs" "cv_bridge" "image_transport")
set(offloadable_face_recognition_BUILDTOOL_DEPENDS "catkin")